language: go
go:
- 1.12.x

services:
- rabbitmq

before_install:
- export GO111MODULE=on
- go get github.com/golang/lint/golint
- go get github.com/gordonklaus/ineffassign
- go get github.com/fzipp/gocyclo
- go get github.com/client9/misspell/cmd/misspell
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- "./pre-commit"
- GO111MODULE=on make test
- GO111MODULE=on make build-all
- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

before_deploy:
- zip rabtap-${TRAVIS_TAG}-windows-amd64.zip bin/rabtap-win-amd64.exe README.md
- zip rabtap-${TRAVIS_TAG}-linux-amd64.zip bin/rabtap-linux-amd64 README.md
- zip rabtap-${TRAVIS_TAG}-darwin-amd64.zip bin/rabtap-darwin-amd64 README.md
- sha256sum *zip > SHASUMS256.txt

deploy:
  provider: releases
  api_key:
    secure: qIDo4H+XPu7xQ/Ga/IT7+SKgqaaUOIMGrp2qtyyMlIR6a98Wm7eseUbiN0ROfx+MhL/3Qt+n3DvtU2qSOy4+jdtBJoOlFaCpb1ARl/xoMQK/DYe28woIBB0uWGBPZeWegPvlf5V2CX5NRoLil6M1SvO7C712Ozjo+8kbAc2yCtHs5/4y4XW21XsAbYBqYEU0f/Rw792RCnQbBIVcrkleQFIn2/PyWKczyLNhzbA5057b7P1YXahGVqW8K2t0ZKnOVXKpjn+nNAeiN+/plHW8MH+021hwTroZtMgKUKfnqbNfkeHQwlgLBbBAh39GDIHF7ItG1tY/Fh49cDSd4Ar2y+qN7e5nf94JxAc8ut6klUyHaa4MD/ggeVLq++3d30EbFdsNblvTddHmhnqC5OHR5VyXmV3s3Y7W3C8nFqLbqHncQWyCfbkPqpT//H3Y4JzWWLFOeqopfHDOIuJ6Js8tQFFT7/AU9iMu0O/yujTgyn+K2oL0B24htncyHB8BFLQvRbIFaosILWNNjG7wotlFpaOTuiu6IizSUOpYmgySD1gk1pVPy279IiGI0r/2sQgLY/CmdB0NkBkz/FuTBUzOY6yPC0HJnwzBFlYYZWHEd6Zmyp5hpvUXWyYIfLaDIdHb4P6jXbstbyNGgToyAwOhUk3nmWNXhc014ffzwiPPV/o=
  file: 
  - rabtap-${TRAVIS_TAG}-windows-amd64.zip
  - rabtap-${TRAVIS_TAG}-linux-amd64.zip
  - rabtap-${TRAVIS_TAG}-darwin-amd64.zip
  - SHASUMS256.txt
  skip_cleanup: true
  on:
    tags: true
env:
  global:
      secure: "Qg/61IYkI7duTQ9r4Jz3hQjdpxH+QMGj2qcYKEhtpfz7i+uS+uj1HE40PuXi4ztagW4VI9+suSKl/EE5MLpT+AsN5RSnUGriDzIF0t4IutmSWkANuLP8oou3i9Op2+r4CKTYKsY2F5nJOrlZRbPIneehPpx65bZx7tFtfRB68gT+JD0i0Na4fFVLaW69wLwtYMPlW8cQseBkYqeQv+SSZhdloXfi+zcIXNbB4LDWrzSmmWEMHJOnxN/c3nbARF1We+GkvhA/L/WXeYUobohEn4UqTU/l7Qf8ohLv68a7K8Z7pub69IdbtQkVbwnJh+8Gx064QI8CD1acC+GIM1tqaLMtHJM3MPUgm2mw255V/qwZdd3Ue7+U5UAPV4xZpAWS/lLZgGK7hoWoXkO/eT8jS3GoArT+cX9lKkT5cBwoPXq/AohzUGpP42NQcg6UcF0oebeq9n9X0lk4boyBLckPNDy5QXvA/yKhCvrfL3IlPDVe70DBt3yyyoZUdYOqcGqtme5RXSXs7hiMn1h6K8xJxRX9IZVg5TddKRyII7wdeWq0lNTPrP+Vyf5O5Zn1ZF/SuUPYXWjl68dW5QpucXPdm4OZRvLNlRxqV8FeOhRm23RqOxx5HeUK+ugUKCBtycjg+Sv8mnPCIoCjJQ2Wx6hZUhBnEg/8cMzCV24DO2NffmE="
